export default {
    actionType: {
        SEARCH_RESULT_SUCCESS: 'SEARCH_RESULT_SUCCESS',
        SEARCH_RESULT_FAILURE: 'SEARCH_RESULT_FAILURE',
        SEARCH_COMPANY_RESULT_SUCCESS: 'SEARCH_COMPANY_RESULT_SUCCESS',
        SEARCH_COMPANY_RESULT_FAILURE: 'SEARCH_COMPANY_RESULT_FAILURE',
    }
}